### ISSUE TITLE
Line 156 of HlpHashResult - Missing ConvertBytesToString

### ISSUE THREAD

**Issue by tedsmith** [Xor-el/HashLib4Pascal#10]
**Describe the bug**
When installing the latest (as of 18/07/19) Freepascal package into Lazarus v2.0.2 (FPC 3.0.4) the compiler complains about line 156 of HlpHashResult in src\Base\HlpHashResult.pas stating : HlpHashResult.pas(156,18) Error: identifier idents no member "ConvertBytesToString"

On examination of TConverters, there is no ConvertBytesToString function or procedure, but there is "ConvertBytesToHexString" and "ConvertHexStringToBytes", but the parameters they expect also differ, requiring a Boolean value. 

**To Reproduce**
1. Download the latest code of master branch.
2. Launch Lazarus v2.0.2 and use the menu to select Package --> Open Package File
3. Select HashLib4Pascal\HashLib\src\Packages\FPC\HashLib4PascalPackage.lpk
4. Click Compile. The error message appears. 
![Untitled](https://user-images.githubusercontent.com/1560598/61482801-5f8eee00-a993-11e9-9b0e-dd38ce0baaa0.png)

**Expected behavior**
Successful compilation and then installation of the package into Lazarus. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 64-bit
 - Freepascal v3.0.4
 - Package Version : Current master

**Comment by Xor-el** [comment]
@tedsmith , sorry but I cannot reproduce this issue.
Are you sure your Lazarus/FPC installation is not corrupted?
My Travis CI builds and runs successfully.
[Travis CI](https://travis-ci.org/Xor-el/HashLib4Pascal)

Besides the method ConvertBytesToString can be found here
https://github.com/Xor-el/HashLib4Pascal/blob/9c0094620caf47f29e168811bf505d997aeee7b1/HashLib/src/Utils/HlpConverters.pas#L90-L91

**Comment by tedsmith** [comment]
Sorry, yes. It seems the fault is my end. I have downloaded to another Windows virtual machine and it worked perfectly. So I have no idea how or why that was coming up on my other machine but it clearly a local issue so I will close. Thanks for looking into it so quickly.
