### ISSUE TITLE
Quick Start and Document needed

### ISSUE THREAD

**Issue by landall** [Xor-el/HashLib4Pascal#11]
**Is your feature request related to a problem? Please describe.**
I cannot quickly know how to use this library.

**Describe the solution you'd like**
Beg a wiki or a quick start document.

**Describe alternatives you've considered**

**Additional context**

**Comment by Xor-el** [comment]
Hi @landall , 
For now there is no quick start wiki for this library, sorry about that.
But not withstanding, you can see a lot usage examples in the unit tests codebase [here](https://github.com/Xor-el/HashLib4Pascal/tree/master/HashLib.Tests).
If the above is not enough, feel free to let me know how I can be of help.

Regards.

**Comment by landall** [comment]
Can you show me some simple code with uses clause to calculate crc and sha1?
I can not find the way from the test case.

**Comment by landall** [comment]
Maybe some code in README.MD is a good advice.

**Comment by Xor-el** [comment]
> Can you show me some simple code with uses clause to calculate crc and sha1?
> I can not find the way from the test case.

What CRC exactly?
CRC32 PKZIP??

What data type do you want to compute hashes for? Byte array or strings?

**Comment by landall** [comment]
> > Can you show me some simple code with uses clause to calculate crc and sha1?
> > I can not find the way from the test case.
> 
> What CRC exactly?
> CRC32 PKZIP??
> 
> What data type do you want to compute hashes for? Byte array or strings?

I want to calculate the crc32 checksum for a file to upload to OneDrive.

**Comment by Xor-el** [comment]
`
uses 
HlpHashFactory;
.....
var
HashResult: String;
begin
HashResult := THashFactory.TChecksum.TCRC.CreateCRC32_PKZIP.ComputeFile(FileName).ToString();
end;

`

**Comment by landall** [comment]
Thanks a lot! The code is so clear!

**Comment by Xor-el** [comment]
@landall , you are welcome.
