### ISSUE TITLE
Code example?

### ISSUE THREAD

**Issue by EganSolo** [Xor-el/HashLib4Pascal#13]
Would it be possible to get an example of using murmur3 or another function in a simple program? I have tried to understand the code but it is non-trivial. A "Hello World" would help as in the following code where "HashFunction" can be replaced by a call to murmu3 hash function.

Program TryHash;
Var S : String;
     hashValue : Cardinal;
begin
  S                := 'Hello World';
  HashValue := HashFunction(S);
Writeln(S, hashValue);
end.

**Comment by Xor-el** [comment]
Hi, from your code description I see your want the result of murmur hash as a Cardinal so I wrote my answer that way.
You can also get your output result as a byte array, HexString and other types.
for more examples, please see the [Unit Tests](https://github.com/Xor-el/HashLib4Pascal/tree/master/HashLib.Tests/src)

```pascal
program TryHash;

uses
  SysUtils,
  HlpHashFactory;

var
  S: string;
  HashValue: Cardinal;
begin
  S := 'Hello World';
  HashValue := THashFactory.THash32.CreateMurmurHash3_x86_32().ComputeString(S,
    TEncoding.UTF8).GetUInt32();
  Writeln(Format('%s Hash of "%s" as UInt32 is %d',
    ['MurmurHash3_x86_32', S, HashValue]));
  ReadLn;
end.
```

**Comment by EganSolo** [comment]
Thank you Xor-el. That's very helpful! Great library!
