### ISSUE TITLE
Resourcestrings are in title caps

### ISSUE THREAD

**Issue by maelh** [Xor-el/HashLib4Pascal#20]
Several resourcestrings are in title caps, eventhough they are error messages and not meant to be shown in a caption/title.
Some would also benefit from added parameters instead of saying "current index" or "current datastructure".

**Comment by Xor-el** [comment]
Actually, I would like to know what standards defines that error messages cannot be shown in caps (genuinely asking).
also, as regards your other comment, I am open to pull requests to address it.

**Comment by maelh** [comment]
I don't have a reference that spells it out explicitly, this is the closest I could find: https://docs.microsoft.com/en-us/windows/win32/uxguide/text-ui

In the screenshot you can see that the caption is in Title Caps and the rest of the message body in normal casing (sentence casing).
That's how it's almost everywhere.

Here is some discussion about the topic:
https://stackoverflow.com/questions/2371226/capitalizing-texts-in-user-interface
https://ux.stackexchange.com/questions/28297/should-we-use-title-case-or-sentence-case-for-headlines-and-buttons

The consensus seems to be to prefer sentence case in general. But until Vista (or maybe Windows 8) to use title case in captions. Title Case in caption seems to be American, sentence case in captions seems to be British. Both though agree on using sentence case in message text/body.

I'll add pull requests :)

**Comment by maelh** [comment]
Actually, the document I linked first does spell it out explicitly, further down below:
https://docs.microsoft.com/en-us/windows/win32/uxguide/text-ui#capitalization

**Comment by Xor-el** [comment]
Thanks for your response. If you can provide a pull request to address this, I will be happy to merge it. 😁😁

**Comment by maelh** [comment]
Here is the pull request: https://github.com/Xor-el/HashLib4Pascal/pull/21

**Comment by Xor-el** [comment]
thanks for your PR, I have merged it.
