### ISSUE TITLE
CRC8 Exception

### ISSUE THREAD

**Issue by hafedh-trimeche** [Xor-el/HashLib4Pascal#23]
Invoking this function generated an exception:
```
function CRC8(const Buffer;const Size:Integer):UInt8;
var
  CRC : IHash;
begin
  if @Buffer=nil then Exit(0);
  CRC    := THashFactory.TChecksum.TCRC.CreateCRC(HlpCRC.CRC8);
  Result := CRC.ComputeUntyped(Buffer,Size).GetUInt8;
end;

```
Exception class EInvalidOperationHashLibException with message 'The size of the byte array (2) and integer type (1) have to match.'. 

Best regards.

**Comment by Xor-el** [comment]
Hi, CRC8 can not fit into a byte since it is an Int16/UInt16,.
I suggest you use the GetUInt16 overload.
