### ISSUE TITLE
HlpTiger.pas F2084 Internal Error: URW1147

### ISSUE THREAD

**Issue by Uefi1** [Xor-el/HashLib4Pascal#25]
hello, I can't compile the project due to an error:
[DCC Fatal Error] HlpTiger.pas(1115): F2084 Internal Error: URW1147
Delphi XE2

**Comment by Xor-el** [comment]
Hello @Uefi1, unfortunately I cannot look into this because I don't have a copy of XE2 installed.
However, can you please try disabling code inlining as I suspect that might be the issue.

**Comment by Uefi1** [comment]
> Hello @Uefi1, unfortunately I cannot look into this because I don't have a copy of XE2 installed. However, can you please try disabling code inlining as I suspect that might be the issue.
No, turned it off didn't help

**Comment by Uefi1** [comment]
I need an answer to this, how can I fix this?

**Comment by Xor-el** [comment]
Hello,  this is an internal compiler error that could come from a couple of issues. 
Could be the use of inline or generics/generic arrays, usage of static or something as simple as using open arrays as arguments.
Unfortunately I don't have access to XE2 to test.
At the moment,  I only have access to Delphi 10.4 and this builds and runs ok there.

I would suggest you upgrade your Delphi version to something modern say 10.4 or higher.
I don't have the zeal or ability to support older Delphi versions as they have a lot of internal compiler bugs.

**Comment by Uefi1** [comment]
> I would suggest you upgrade your Delphi version to something modern say 10.4 or higher.

Hail, successfully compiled the package from Delphi XE2 by removing inline in HlpHashBuffer.pas
It was: 
function Clone(): THashBuffer; inline;
became:
function Clone(): THashBuffer;

**Comment by Xor-el** [comment]
First of all, Congratulations.
Just wanted to point out, hope you are aware that removing `inline;` will in most cases hurt performance a lot.
If that is a sacrifice you are willing to go with, then it's fine.
